/*
 * Optimal merging strategy for annotation lines.
 * Uses branch-and-bound backtracking to find the global optimum grouping
 * that minimizes the total number of final annotation lines.
 * 
 * Generated by ChatGPT based on the original implementation of a greedy merging strategy.
 * 
 * Merge criteria: 
    * lowest difference of weighted average Y-distance of the annotation lines
    * lowest number of annotation lines in the group
    * lowest number of conflicting intervals with other lines
 */

interface IntervalSnapshot {
    start: number;
    end: number;
}

interface LineForMerge {
    getMergeCriteria(): number;
    merge(other: LineForMerge): boolean;
    usedIntervals: { start: number; end: number }[];
}

const areIntervalsConflicting = (left: IntervalSnapshot, right: IntervalSnapshot): boolean => {
    const overlaps = left.start < right.end && left.end > right.start;
    if (!overlaps) {
        return false;
    }
    const sameInterval = left.start === right.start && left.end === right.end;
    return !sameInterval;
};

const getContinuousClusterSignature = (intervals: IntervalSnapshot[]): string => {
    if (intervals.length === 0) {
        return "";
    }

    const sorted = [...intervals].sort((a, b) => a.start - b.start || a.end - b.end);
    const clusters: IntervalSnapshot[] = [];

    sorted.forEach(interval => {
        const lastCluster = clusters[clusters.length - 1];
        if (!lastCluster) {
            clusters.push({ start: interval.start, end: interval.end });
            return;
        }

        if (interval.start <= lastCluster.end) {
            lastCluster.end = Math.max(lastCluster.end, interval.end);
            return;
        }

        clusters.push({ start: interval.start, end: interval.end });
    });

    return clusters.map(cluster => `${cluster.start}:${cluster.end}`).join("|");
};

const preMergeIdenticalContinuousClusters = <T extends LineForMerge>(lines: T[]): T[] => {
    if (lines.length <= 1) {
        return lines;
    }

    const groupsByCluster = new Map<string, T[]>();
    lines.forEach(line => {
        const signature = getContinuousClusterSignature(line.usedIntervals);
        const group = groupsByCluster.get(signature);
        if (group) {
            group.push(line);
            return;
        }
        groupsByCluster.set(signature, [line]);
    });

    const preMerged: T[] = [];
    groupsByCluster.forEach(group => {
        if (group.length === 1) {
            preMerged.push(group[0]);
            return;
        }

        const survivors: T[] = [];
        group.forEach(line => {
            const mergeTarget = survivors.find(candidate => candidate.merge(line));
            if (!mergeTarget) {
                survivors.push(line);
            }
        });
        preMerged.push(...survivors);
    });

    return preMerged;
};

const findOptimalMergeGroups = (lines: LineForMerge[]): number[][] => {
    if (lines.length <= 1) {
        return lines.length === 1 ? [[0]] : [];
    }

    const snapshots = lines.map((line, index) => ({
        index,
        mergeCriteria: line.getMergeCriteria(),
        intervals: line.usedIntervals.map(i => ({ start: i.start, end: i.end })),
    }));

    const incompatible = Array.from({ length: snapshots.length }, () => Array(snapshots.length).fill(false));
    for (let i = 0; i < snapshots.length; i++) {
        for (let j = i + 1; j < snapshots.length; j++) {
            const hasConflict = snapshots[i].intervals.some(left => snapshots[j].intervals.some(right => areIntervalsConflicting(left, right)));
            incompatible[i][j] = hasConflict;
            incompatible[j][i] = hasConflict;
        }
    }

    const order = snapshots
        .map((_, idx) => idx)
        .sort((a, b) => {
            const aConflicts = incompatible[a].filter(Boolean).length;
            const bConflicts = incompatible[b].filter(Boolean).length;
            if (aConflicts !== bConflicts) {
                return bConflicts - aConflicts;
            }
            if (snapshots[a].intervals.length !== snapshots[b].intervals.length) {
                return snapshots[b].intervals.length - snapshots[a].intervals.length;
            }
            return a - b;
        });

    type Bucket = {
        members: number[];
        intervalCounts: Map<string, number>;
        intervals: IntervalSnapshot[];
        criteriaSum: number;
        criteriaCount: number;
    };

    const createEmptyBucket = (): Bucket => ({
        members: [],
        intervalCounts: new Map<string, number>(),
        intervals: [],
        criteriaSum: 0,
        criteriaCount: 0,
    });

    const canPlace = (lineIndex: number, bucket: Bucket): boolean => {
        const candidateIntervals = snapshots[lineIndex].intervals;
        return candidateIntervals.every(candidate => bucket.intervals.every(existing => !areIntervalsConflicting(existing, candidate)));
    };

    const addLineToBucket = (lineIndex: number, bucket: Bucket): void => {
        bucket.members.push(lineIndex);
        const criteria = snapshots[lineIndex].mergeCriteria;
        bucket.criteriaSum += criteria;
        bucket.criteriaCount += 1;

        snapshots[lineIndex].intervals.forEach(interval => {
            const key = `${interval.start}:${interval.end}`;
            const previousCount = bucket.intervalCounts.get(key) ?? 0;
            if (previousCount === 0) {
                bucket.intervals.push(interval);
            }
            bucket.intervalCounts.set(key, previousCount + 1);
        });
    };

    const removeLineFromBucket = (lineIndex: number, bucket: Bucket): void => {
        bucket.members.pop();
        const criteria = snapshots[lineIndex].mergeCriteria;
        bucket.criteriaSum -= criteria;
        bucket.criteriaCount -= 1;

        snapshots[lineIndex].intervals.forEach(interval => {
            const key = `${interval.start}:${interval.end}`;
            const previousCount = bucket.intervalCounts.get(key) ?? 0;
            if (previousCount <= 1) {
                bucket.intervalCounts.delete(key);
                const intervalIndex = bucket.intervals.findIndex(i => i.start === interval.start && i.end === interval.end);
                if (intervalIndex >= 0) {
                    bucket.intervals.splice(intervalIndex, 1);
                }
                return;
            }
            bucket.intervalCounts.set(key, previousCount - 1);
        });
    };

    let bestBucketCount = snapshots.length;
    let bestGroups: number[][] = snapshots.map((_, idx) => [idx]);
    const buckets: Bucket[] = [];

    const backtrack = (position: number): void => {
        if (buckets.length >= bestBucketCount) {
            return;
        }

        if (position >= order.length) {
            bestBucketCount = buckets.length;
            bestGroups = buckets.map(bucket => [...bucket.members]);
            return;
        }

        const lineIndex = order[position];
        const lineCriteria = snapshots[lineIndex].mergeCriteria;
        const candidateBucketIndexes = buckets
            .map((bucket, idx) => ({
                idx,
                score: Math.abs((bucket.criteriaSum / bucket.criteriaCount) - lineCriteria),
            }))
            .sort((a, b) => a.score - b.score)
            .map(x => x.idx);

        for (const bucketIndex of candidateBucketIndexes) {
            const bucket = buckets[bucketIndex];
            if (!canPlace(lineIndex, bucket)) {
                continue;
            }
            addLineToBucket(lineIndex, bucket);
            backtrack(position + 1);
            removeLineFromBucket(lineIndex, bucket);
        }

        const newBucket = createEmptyBucket();
        addLineToBucket(lineIndex, newBucket);
        buckets.push(newBucket);
        backtrack(position + 1);
        buckets.pop();
    };

    backtrack(0);

    return bestGroups
        .map(group => group.map(idx => snapshots[idx].index).sort((a, b) => a - b))
        .sort((a, b) => a[0] - b[0]);
};

/**
 * Apply optimal merging strategy to annotation lines.
 * Finds the globally optimal grouping that minimizes the total number of final lines.
 *
 * @param linesWithAnnotations Array of lines to merge
 * @returns Array of merged lines in optimal grouping
 */
export function optimalAnnotationLinesMerge<T extends LineForMerge>(linesWithAnnotations: T[]): T[] {
    if (linesWithAnnotations.length === 0) {
        return [];
    }

    // Fast-path optimization: merge lines that share identical continuous interval clusters.
    // This can significantly reduce the branch-and-bound search space for the global optimizer.
    const preMergedLines = preMergeIdenticalContinuousClusters(linesWithAnnotations);
    if (preMergedLines.length <= 1) {
        return preMergedLines;
    }

    // Find globally optimal merge groups: minimize the number of final annotation lines.
    const optimalMergeGroups = findOptimalMergeGroups(preMergedLines);
    const mergedLines = optimalMergeGroups.map(group => {
        const [headIndex, ...restIndexes] = group;
        const mergedLine = preMergedLines[headIndex];
        restIndexes.forEach(index => {
            mergedLine.merge(preMergedLines[index]);
        });
        return mergedLine;
    });

    return mergedLines;
}
